version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: docker/web/Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    environment:
      - NODE_ENV=development
    command: sh -c "npm install && npm run dev"