version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: docker/web/Dockerfile.prod
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    restart: unless-stopped